import { Feedstock, MeasureUnit } from "@/types/objects/feedstock"

const feedstocks: Feedstock[] = [
    {
        id: "1",
        name: "Harina de trigo",
        description: "Harina refinada para panadería",
        measure_unit: MeasureUnit.KILOGRAMMS,
        unit_cost: 45.5,
        provider: "Molinos Río de la Plata",
        created_at: new Date("2025-01-15T10:00:00Z"),
        updated_at: new Date("2025-06-10T14:30:00Z"),
        is_deleted: false,
    },
    {
        id: "2",
        name: "Huevos",
        description: "Huevos de gallina, docena",
        measure_unit: MeasureUnit.UNIT,
        unit_cost: 120.0,
        provider: "Granja El Sol",
        created_at: new Date("2025-03-20T08:30:00Z"),
        updated_at: new Date("2025-06-01T09:15:00Z"),
        is_deleted: false,
    },
    {
        id: "3",
        name: "Mano de obra",
        description: "Costo por hora de trabajo",
        measure_unit: MeasureUnit.HOURS,
        unit_cost: 1500.0,
        provider: null,
        created_at: new Date("2025-02-10T12:00:00Z"),
        updated_at: new Date("2025-06-20T13:00:00Z"),
        is_deleted: null,
    },
    {
        id: "4",
        name: "Aceite vegetal",
        description: "Aceite de girasol en bidón de 5L",
        measure_unit: MeasureUnit.KILOGRAMMS,
        unit_cost: 180.75,
        provider: "Aceitera General Deheza",
        created_at: new Date("2025-01-28T15:45:00Z"),
        updated_at: new Date("2025-05-18T11:20:00Z"),
        is_deleted: false,
    },
    {
        id: "5",
        name: "Sal fina",
        description: "Sal para uso alimenticio",
        measure_unit: MeasureUnit.KILOGRAMMS,
        unit_cost: 22.0,
        provider: "Salinera del Norte",
        created_at: new Date("2025-03-05T07:00:00Z"),
        updated_at: new Date("2025-06-25T08:00:00Z"),
        is_deleted: false,
    },
    {
        id: "6",
        name: "Botellas de vidrio",
        description: "Botellas vacías retornables",
        measure_unit: MeasureUnit.UNIT,
        unit_cost: 50.0,
        provider: "Cristalería San Carlos",
        created_at: new Date("2025-01-10T10:10:00Z"),
        updated_at: new Date("2025-06-03T16:00:00Z"),
        is_deleted: null,
    },
    {
        id: "7",
        name: "Azúcar",
        description: "Azúcar blanca refinada",
        measure_unit: MeasureUnit.KILOGRAMMS,
        unit_cost: 60.3,
        provider: "Ledesma",
        created_at: new Date("2025-02-25T13:00:00Z"),
        updated_at: new Date("2025-06-15T14:00:00Z"),
        is_deleted: false,
    },
    {
        id: "8",
        name: "Transporte externo",
        description: "Servicio de flete por hora",
        measure_unit: MeasureUnit.HOURS,
        unit_cost: 2200.0,
        provider: "Logística Sur",
        created_at: new Date("2025-04-02T10:20:00Z"),
        updated_at: new Date("2025-06-29T12:00:00Z"),
        is_deleted: false,
    },
    {
        id: "9",
        name: "Cajas de cartón",
        description: "Cajas para embalaje",
        measure_unit: MeasureUnit.UNIT,
        unit_cost: 35.0,
        provider: "Empaque Plus",
        created_at: new Date("2025-05-10T09:00:00Z"),
        updated_at: new Date("2025-06-10T10:00:00Z"),
        is_deleted: false,
    },
    {
        id: "10",
        name: "Otros insumos",
        description: "Materiales varios",
        measure_unit: MeasureUnit.OTHERS,
        unit_cost: 100.0,
        provider: "Varios",
        created_at: new Date("2025-01-01T00:00:00Z"),
        updated_at: new Date("2025-06-30T00:00:00Z"),
        is_deleted: true,
    },
]

export default feedstocks
